config/routes.rb
Rails.application.routes.draw do

  root :to => 'sounds#index'

  resources :user_sessions
  resources :users
  resources :sounds

  get 'login' =>  'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post '/sounds/create_via_blob' => 'sounds#create_via_blob'

end

app/models/sound.rb
class Sound < ActiveRecord::Base
  belongs_to :user 

  geocoded_by :city_country, :latitude => :latitude, :longitude => :longitude
  #after_validation :geocode, if: :name_changed?

  mount_uploader :echo, EchoUploader

  def city_country
    user.city + ',' + user.country
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :sounds

  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :email, uniqueness: true

  geocoded_by :city 
  after_validation :geocode

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :require_login 

  private
  def not_authenticated
    redirect_to login_path, alert: "Please login first"
  end
  

end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  skip_before_filter :require_login, only: [:index, :create, :show]

  def index
    @sound = Sound.new

    @sound.echo = params[:echo]
    @sounds = if params[:latitude] && params[:longitude] 
       Sound.near([params[:latitude], params[:longitude]], 0.7, ASC)
    else
      Sound.all    
    end
        
    respond_to do |format|
      format.html
      format.js 
    end  
  end

  def new
    @sound = Sound.new
    @sound.user = current_user
   # assign_location
  end

  def create_via_blob
    @sound = Sound.new
    @sound.user_id = current_user.id
    @sound.echo = params[:echo]
    @sound.save
    render :js => "window.location = '/sounds/#{@sound.id}/edit'"
  end

  def create
    @sound = Sound.new(sound_params)
    @sound.user = current_user
    @sound.echo = params[:echo]

    if @sound.save
      render :js => "window.location = '/sounds/#{@sound.id}'"
    else
      render action: 'new'   
    end
  end

  def show
    @sound = Sound.find(params[:id])
    @nearby_sounds = @sound.nearbys(2, :units => :km)


  end


  def edit
    @sound = Sound.find(params[:id])
  end

  def update
    @sound = Sound.find(params[:id])

    @sound.name = params[:sound][:name]
    @sound.sound_url = params[:sound] [:sound_url]
    @sound.description = params[:sound][:description]

    if @sound.save
      redirect_to @sound
    else
      render 'edit'
    end  

  end

  def destroy
    @sound = Sound.find(params[:id])
    @sound.destroy

    redirect_to sounds_path
  end

  private

  def sound_params
    params.require(:sound).permit(:name, :description, :latitude, :longitude, :sound_url)
  end

  # def assign_location
  #   location = request.location
  #   @sound.latitude = location.latitude
  #   @sound.longitude = location.longitude    
  # end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])

      redirect_back_or_to(:users, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end   
  end

  def destroy
    logout
    redirect_to(:sounds, notice: 'Logged out!')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
    @users = User.all

    @user_geo_lat = params[:latitude]
    @user_geo_long = params[:longitude]
    
  end  

  def new
    @user = User.new 
  end

  def create
    @user = User.new(user_params)

    if @user.save 
     login(@user.email, user_params[:password])
     redirect_to(user_path(@user), notice: 'Welcome to the World of Echoes')
   else
    render action: 'new'  
  end
end

def show
  @user = User.find(params[:id])
end

def edit
  @user = User.find(params[:id])
end


def update
  @user = User.find(params[:id])

  @user.name = params[:user][:name]
  @user.email = params[:user][:email]
  @user.city = params[:user][:city]
  @user.country = params[:user][:country]
  @user.description = params[:user][:description]
  @user.password = params[:user][:password]
  @user.password_confirmation = params[:user][:password_confirmation]


  if @user.save
    redirect_to @user
  else
    render 'edit'
  end  
end

def destroy
end

private 

def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation, :city, :country, :latitude, :longitude)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Echoes</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=#{Figaro.env.google_maps_api}&sensor=true" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <!--     <h1>Echoes</h1> -->
    <nav>
      <% if current_user %>
      <div class="nav-left"> 
        <ul class="navigation"> 
          <li><%= link_to "Home", sounds_path %> </li>  
          <li><a href="<%= new_sound_path %>">Record</a></li>
          <li><a id="current_location">Find Nearby Sounds</a></li> 
        </ul>
      </div>

      <div class="nav-right">
        <ul class="navigation"> 
          <li><%= link_to "View Profile", user_path(current_user.id) %></li> 
          <li><%= link_to "Logout", :logout, method: :post %></li>
        </ul>
      </div>


      <%  else %>
      <div class="nav-left"> 
        <ul class="navigation"> 
          <li><a href="<%= new_sound_path %>">Share</a></li>   
          <li><a id="current_location">Explore</a></li> 
        </ul>
      </div>

      <div class="nav-right">
        <ul class="navigation"> 
          <li><%= link_to "Sign Up", new_user_path %> </li>
          <li><%= link_to "Login", :login %> </li>
        </ul>
      </div>

      <% end %>
    </nav>
  </header>

<div class="clear"></div>



  <%= yield %>
  


  <div>
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>

</body>



<footer>
  An All About Drama design.

</footer>
</html>

app/views/sounds/_sound.html.erb
<p>  
 <% if sound.echo_url != nil %>
   <%= audio_tag(sound.echo, controls: true) %> 
 <% else %>
  <%= audio_tag(sound.sound_url, controls: true) %> 
 <% end %>
  
<%= link_to sound.name, sound_path(sound) %> 

</p>

app/views/sounds/create.html.erb
<h1>Sounds#create</h1>
<p>Find me in app/views/sounds/create.html.erb</p>

app/views/sounds/destroy.html.erb
<h1>Sounds#destroy</h1>
<p>Find me in app/views/sounds/destroy.html.erb</p>

app/views/sounds/edit.html.erb
<h2> Edit: "<%= @sound.name %>"" </h2>

<%= form_for :sound, url: sound_path, method: :patch do |f| %>


<% if @sound.errors.any? %>

<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @sound.errors.full_messages %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<p>
  <%= f.label :name  %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :sound_url %><br>
  <%= f.text_field :echo%>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>



<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Back to Sound', sound_path(@sound) %>

app/views/sounds/index.html.erb
<hr>

<div id="map-canvas"></div>
<hr>

<div class="container">


<section id="sound-list">
 <h2>Sounds</h2>
 <%= render @sounds %>
</section>

<%= javascript_tag do %>
  window.latitude = <%= @sounds.last.latitude.to_f %>;
  window.longitude = <%= @sounds.last.longitude.to_f %>;
  window.showMarker = true;    

  if (navigator.geolocation) {
    var timeoutVal = 10 * 1000 * 1000;
    navigator.geolocation.getCurrentPosition(
      displayPosition, 
      displayError,
      { enableHighAccuracy: true, timeout: timeoutVal, maximumAge: 0 }
    );
  }
  else {
    alert("Geolocation is not supported by this browser");
  }
  
<% end %>

</div>

app/views/sounds/index.js.erb
$('#sound-list').html("<%= j(render @sounds) %>");
 
var coords = window.coords = <%= raw @sounds.map {|r| {latitude: r.latitude.to_f, longitude: r.longitude.to_f}}.to_json %>;
clearMarkers(coords);
addMarkers(coords);

app/views/sounds/new.html.erb
<h1>Record a new sound</h1>

<%= form_for @sound do |f| %>
<% if @sound.errors.any? %>
<div class="error_messages">
  <h3>Form is invalid</h3>
  <ul>
    <% for message in @sound.errors.full_messages %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>
  
<button id="start">record</button>
<button id="stop">stop</button>
  
<p id="output"></p>

<ul id="recordingslist"></ul>

<div class="form_field">
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
 <br>
<%= f.hidden_field :latitude  %>
<%= f.hidden_field :longitude %>

<div class="form_field">
  <%= f.label :description%>
  <%= f.text_field :description %>
</div>
<br>
<div class="form_actions"><%= f.submit "Create Sound", {id: 'submit_new_sound'} %></div>
<% end %>
<br>
<div>
<%= link_to 'Back to Sounds', sounds_path %>
</div>

<script>

 // variables
 var leftchannel = [];
 var rightchannel = [];
 var recorder = null;
 var recording = false;
 var recordingLength = 0;
 var volume = null;
 var audioInput = null;
 var sampleRate = 44100;
 var audioContext = null;
 var context = null;
 var outputElement = document.getElementById('output');
 var outputString;

// feature detection 
if (!navigator.getUserMedia)
  navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia ||
navigator.mozGetUserMedia || navigator.msGetUserMedia;

if (navigator.getUserMedia){
  navigator.getUserMedia({audio:true}, success, function(e) {
    alert('Error capturing audio.');
  });
} else 
  alert('Access to the microphone supported in this browser.');

  $('#start').on('click', function(e) {
    e.preventDefault();
    startRecording();
  });

  $('#stop').on('click', function(e) {
    e.preventDefault();
    stopRecording();
  });
  
  $('#submit_new_sound').click(function(ev) {
    ev.preventDefault();

    var formData = new FormData($('#new_sound')[0]);
    formData.append("echo", window.blob, window.filename);
    console.log(formData);
    $.ajax({
      url: '/sounds',
      type: 'POST',
      data: formData,
      processData: false,
      contentType: false
    });  
  });

  function startRecording() {
    $('#stop').prop("disabled", false);
    // $('#myform').latitude.hide();
    recording = true;
    // reset the buffers for the new recording
    leftchannel.length = rightchannel.length = 0;
    recordingLength = 0;
    outputElement.innerHTML = 'Recording now...';    
  }

  function stopRecording() {
    // we stop recording
    recording = false;
    
    outputElement.innerHTML = 'Preview your sound, add a name and description:';

    // we flat the left and right channels down
    var leftBuffer = mergeBuffers ( leftchannel, recordingLength );
    var rightBuffer = mergeBuffers ( rightchannel, recordingLength );
    // we interleave both channels together
    var interleaved = interleave ( leftBuffer, rightBuffer );
    
    // we create our wav file
    var buffer = new ArrayBuffer(44 + interleaved.length * 2);
    var view = new DataView(buffer);
    
    // RIFF chunk descriptor
    writeUTFBytes(view, 0, 'RIFF');
    view.setUint32(4, 44 + interleaved.length * 2, true);
    writeUTFBytes(view, 8, 'WAVE');
    // FMT sub-chunk
    writeUTFBytes(view, 12, 'fmt ');
    view.setUint32(16, 16, true);
    view.setUint16(20, 1, true);
    // stereo (2 channels)
    view.setUint16(22, 2, true);
    view.setUint32(24, sampleRate, true);
    view.setUint32(28, sampleRate * 4, true);
    view.setUint16(32, 4, true);
    view.setUint16(34, 16, true);
    // data sub-chunk
    writeUTFBytes(view, 36, 'data');
    view.setUint32(40, interleaved.length * 2, true);
    
    // write the PCM samples
    var lng = interleaved.length;
    var index = 44;
    var volume = 1;
    for (var i = 0; i < lng; i++){
      view.setInt16(index, interleaved[i] * (0x7FFF * volume), true);
      index += 2;
    }
    
    // our final binary blob
    window.blob = new Blob ( [ view ], { type : 'audio/wav' } );
    console.log("blob!");
    
    // let's save it locally
    var url = URL.createObjectURL(blob);
    var li = document.createElement('li');
    var au = document.createElement('audio');
    var hf = document.createElement('a');

    au.controls = true;
    au.src = url;
    hf.href = url;
    window.filename = new Date().toISOString() + '.wav';
    // hf.innerHTML = hf.download;
    li.appendChild(au);
    li.appendChild(hf);
    recordingslist.appendChild(li);
    $('#stop').prop("disabled", true);
  }

    function dataURLtoBlob(dataURL) {
      // Decode the dataURL    
      var binary = atob(dataURL.split(',')[1]);
      // Create 8-bit unsigned array
      var array = [];
      for(var i = 0; i < binary.length; i++) {
        array.push(binary.charCodeAt(i));
      }
      // Return our Blob object
      return new Blob([new Uint8Array(array)], {type: 'audio/wav'});
    }

    function interleave(leftChannel, rightChannel){
      var length = leftChannel.length + rightChannel.length;
      var result = new Float32Array(length);

      var inputIndex = 0;

      for (var index = 0; index < length; ){
        result[index++] = leftChannel[inputIndex];
        result[index++] = rightChannel[inputIndex];
        inputIndex++;
      }
      return result;
    }

    function mergeBuffers(channelBuffer, recordingLength){
      var result = new Float32Array(recordingLength);
      var offset = 0;
      var lng = channelBuffer.length;
      for (var i = 0; i < lng; i++){
        var buffer = channelBuffer[i];
        result.set(buffer, offset);
        offset += buffer.length;
      }
      return result;
    }

    function writeUTFBytes(view, offset, string){ 
      var lng = string.length;
      for (var i = 0; i < lng; i++){
        view.setUint8(offset + i, string.charCodeAt(i));
      }
    }

    function success(e){
    // creates the audio context
    audioContext = window.AudioContext || window.webkitAudioContext;
    context = new audioContext();

    // creates a gain node
    volume = context.createGain();

    // creates an audio node from the microphone incoming stream
    audioInput = context.createMediaStreamSource(e);

    // connect the stream to the gain node
    audioInput.connect(volume);

    /* From the spec: This value controls how frequently the audioprocess event is 
    dispatched and how many sample-frames need to be processed each call. 
    Lower values for buffer size will result in a lower (better) latency. 
    Higher values will be necessary to avoid audio breakup and glitches */
    var bufferSize = 2048;
    recorder = context.createScriptProcessor(bufferSize, 2, 2);

    recorder.onaudioprocess = function(e){
      if (!recording) return;
      var left = e.inputBuffer.getChannelData (0);
      var right = e.inputBuffer.getChannelData (1);
        // we clone the samples
        leftchannel.push (new Float32Array (left));
        rightchannel.push (new Float32Array (right));
        recordingLength += bufferSize;
      }

    // we connect the recorder
    volume.connect (recorder);
    recorder.connect (context.destination); 
  }

  </script>


<%= javascript_tag do %>

  function updateSoundLocation(position){
  $('#sound_latitude').val(position.coords.latitude),
  $('#sound_longitude').val(position.coords.longitude)
}

function displayError(error) {
  var errors = { 
    1: 'Permission denied',
    2: 'Position unavailable',
    3: 'Request timeout'
  };
  alert("Error: " + errors[error.code]);
}


if (navigator.geolocation) {
  var timeoutVal = 10 * 1000 * 1000;
  navigator.geolocation.getCurrentPosition(
    updateSoundLocation,
    displayError,
    { enableHighAccuracy: true, timeout: timeoutVal, maximumAge: 0 }
    );
    }
  else {
    alert("Geolocation is not supported by this browser");
}

<% end %>

app/views/sounds/show.html.erb
<hr>
<div id="map-canvas"></div>
<hr>

<article class="sound">
  <h1 class="sound-name"><%= @sound.name %></h1>
  <p> 
    <%= @sound.description %>
  </p>

  <p>
   <% if @sound.echo_url != nil %>
   <%= audio_tag(@sound.echo, controls: true) %> 
   <% else %>
   <%= audio_tag(@sound.sound_url, controls: true) %> 
   <% end %>
 </p>


<p >
  <%= link_to "Edit", edit_sound_path %>
  <%= link_to 'Delete', sound_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  
</p>

 <% if @nearby_sounds.present? %>
 <h2>Nearby Sounds</h2>
 <ul>
  <% @nearby_sounds.each do |ns| %>
  <p>
    <li><%= link_to "#{ns.name}", ns %>: <%= "#{(ns.distance * 100).round.to_f / 100} kms" %></li>
    <% end %>
  </p>
</ul>
<% end %>


</article>



<%= javascript_tag do %>
window.latitude = <%= @sound.latitude.to_f %>;
window.longitude = <%= @sound.longitude.to_f %>;
window.showMarker = true;

window.coords = <%= raw @nearby_sounds.map {|r| {latitude: r.latitude.to_f, longitude: r.longitude.to_f}}.to_json %>

<% end %>

app/views/sounds/update.html.erb
<h1>Sounds#update</h1>
<p>Find me in app/views/sounds/update.html.erb</p>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>

<div class="form_field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  <div class="form_field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="form_actions">
    <%= submit_tag "Login" %>
  </div>

  <% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h2>Login</h2>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>

app/views/users/_form.html.erb
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2> Edit User <%= @user.id %> </h2>

<%= form_for :user, url: user_path, method: :patch do |f| %>


<% if @user.errors.any? %>

<div class="error_messages">
  <h2>Form is invalid</h2>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<p>
  <%= f.label :name  %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>

<p>
  <%= f.label :city  %><br>
  <%= f.text_field :city %>
</p>

<p>
  <%= f.label :country %><br>
  <%= f.text_field :country %>
</p>

<p>
  <%= f.label :description %><br>
  <%= f.text_field :description %>
</p>




<div class="form_field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

 <div class="form_field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>


<p>
  <%= f.submit %>
</p>
<% end %>


<%= link_to 'Back to Users', users_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>

<%= link_to user.email, user_path(user) %> 
<%= user.email %> <br>
<% end %>

app/views/users/new.html.erb
 <h2> Sign up </h2>

<%= form_for @user do |f| %>

<% if @user.errors.any? %>
<div class="error_messages">
  <h3>Form is invalid</h3>
  <ul>
    <% for message in @user.errors.full_messages %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>

<% end %>

<div class="form_field">
  <%= f.label :email %>
  <%= f.email_field :email %>
</div>

<div class="form_field">
  <%= f.label :current_city %>
  <%= f.text_field :city %>
</div>

<div class="form_field">
  <%= f.label :current_country %>
  <%= f.text_field :country %>
</div>

<div class="form_field">
  <%= f.label :password %>
  <%= f.password_field :password %>
</div>

<div class="form_field">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
</div>

<div class="form_actions"><%= f.submit %></div>
<% end %>

<%= link_to 'Back to Users', users_path %>

app/views/users/show.html.erb
<h2> User <%= @user.id %> </h2>

<p>
  <strong>Name: </strong>
  <%= @user.name %>
</p> 

<p>
  <strong>City: </strong>
  <%= @user.city %>
</p> 
<p>
  <strong>Country: </strong>
  <%= @user.country %>
</p>

<!-- <p>
  <strong>Latitude: </strong>
  <%= @user.latitude %>
</p>
<p>
  <strong>Longitude: </strong>
  <%= @user.longitude %>
</p>
 -->
<p>
  <strong>Profile: </strong>
  <%= @user.description %>
</p>


<p>
  <strong>Image: </strong>
  <img src="<%#= @user.image_url %>" > 
</p>




<p>
  <%= link_to "Edit", edit_user_path %>
  <%= link_to 'Delete', user_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  
</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

<%= flash[:message] %>